apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchdog-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchdog-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watchdog-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: watchdog-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: watchdog-role
  apiGroup: rbac.authorization.k8s.io
